# Generated by Django 4.2.4 on 2023-09-01 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('creation_date', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=100)),
                ('company', models.JSONField()),
                ('address', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
