# Generated by Django 4.2.4 on 2023-09-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
