# Generated by Django 4.2.4 on 2023-09-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0002_user_photo_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='user_core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
