# Generated by Django 4.2.4 on 2023-09-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0003_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('thumbnail_url', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('photos', models.ManyToManyField(blank=True, null=True, to='user_core.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
