# Generated by Django 4.2.4 on 2023-09-02 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0004_photo_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo_path',
            new_name='profile_photo_path',
        ),
        migrations.AddField(
            model_name='user',
            name='photos_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='root_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='videos_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
