# Generated by Django 4.2.4 on 2023-09-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0005_rename_photo_path_user_profile_photo_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photos_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='videos_path',
        ),
    ]
