# Generated by Django 4.2.4 on 2023-09-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0007_remove_user_creation_date_user_email_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='bugrahanetemircii@gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
