# Generated by Django 4.2.4 on 2023-09-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0009_user_date_joined_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
