# Generated by Django 4.2.4 on 2023-09-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0010_alter_user_address_alter_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='creation_date',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creation_date',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='creation_date',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='creation_date',
            new_name='date_joined',
        ),
    ]
