# Generated by Django 4.2.4 on 2023-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0011_rename_creation_date_album_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
