# Generated by Django 4.2.4 on 2023-09-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
